name: 🐞 Bug

description: File a bug/issue

title: "Bug: <add a description here>"

labels: [bug]

assignees:
  - jmcnamara

body:

- type: markdown
  attributes:
    value: Please fill in the title above and the mandatory sections below to submit your bug report.

- type: textarea
  attributes:
    label: Current behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Sample code to reproduce
    description: Please add a small, complete, sample program that demonstrates your issue.
    placeholder: |
      some code.
  validations:
    required:  true


- type: checkboxes
  attributes:
    label: OpenOffice and LibreOffice users
    description: OpenOffice and LibreOffice do not always render xlsx files in the same way as Excel. It is important to first check if the issue you are reporting is due tto XlsxWriter or to OpenOffice or LibreOffice.
    options:
    - label: I have tested the output file with Excel.
      required: true

- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false


