name: XlsxWriter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pycodestyle

    - name: Test the code style
      run: |
        ls -1 xlsxwriter/*.py | egrep -v "theme|compat|__init__" | xargs pycodestyle
        pycodestyle --ignore=E501 xlsxwriter/theme.py
        find xlsxwriter/test -name \*.py | xargs pycodestyle --ignore=E501

    - name: Test with pytest
      run: |
        pytest
